version: "3.8"

services:
  ai:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    env_file:
      - .env

  proxy:
    container_name: proxy
    image: nginx:alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    depends_on:
      - ai
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx/ai.conf:/etc/nginx/conf.d/ai.conf
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/srv/certbot
    ports:
      - "80:80"
      - "443:443"
                                                                                                                                                                                              
  certbot:
    container_name: certbot
    restart: always
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/srv/certbot
